openapi: 3.1.0
info:
  title: Ruuvi Cloud - User API
  description: Ruuvi Cloud user facing API. Everything you need to build your own front-end to Ruuvi Cloud.
  version: 1.0.0
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  contact:
    name: Ruuvi Support
    url: https://ruuvi.com/support
    email: support@ruuvi.com

servers:
  - url: https://network.ruuvi.com
  - url: https://testnet.ruuvi.com

tags:
  - name: Air-Firmware
    description: Ruuvi Air firmware update information
  - name: Alerts
    description: Alert management for sensors
  - name: Register-User
    description: User registration and verification
  - name: Sensor-Settings
    description: Sensor settings management
  - name: Push-Notifications
    description: Push notification token management


paths:
  /air_firmwareupdate:
    $ref: 'air-firmware.yaml'
  /alerts:
    $ref: 'alerts.yaml'
  /push-register:
    $ref: 'push-register.yaml'
  /register: 
    $ref: 'register.yaml'
  /sensor-settings:
    $ref: './sensor-settings.yaml'
  /verify: 
    $ref: 'verify.yaml'
  

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    AirFirmwareResponse:
      $ref: '../components/schemas/AirFirmwareResponse.yaml'
    Alert:
      $ref: '../components/schemas/Alert.yaml'
    AlertActionResult:
      $ref: '../components/schemas/AlertActionResult.yaml'
    AlertsResponse:
      $ref: '../components/schemas/AlertsResponse.yaml'
    AlertType:
      $ref: '../components/schemas/AlertType.yaml'
    SensorWithAlerts:
      $ref: '../components/schemas/SensorWithAlerts.yaml'
    Error:
      $ref: '../components/schemas/Error.yaml'
    registerResult:
      $ref: '../components/schemas/registerResult.yaml'
    verifyResult:
      $ref: '../components/schemas/verifyResult.yaml'
    SensorBase:
      $ref: '../components/schemas/SensorBase.yaml'
    SettingGetResult:
      $ref: '../components/schemas/SettingGetResult.yaml'
    SettingObject:
      $ref: '../components/schemas/SettingObject.yaml'
    Settings:
      $ref: '../components/schemas/Settings.yaml'
    SettingSetResult:
      $ref: '../components/schemas/SettingSetResult.yaml'
    Subscription:
      $ref: '../components/schemas/Subscription.yaml'
    Success:
      $ref: '../components/schemas/Success.yaml'
