openapi: 3.0.3
info:
  title: Ruuvi Cloud â€“ User API
  description: Ruuvi Cloud user facing API. Everything you need to build your own front-end to Ruuvi Cloud.
  version: 1.0.0
  contact:
    name: Ruuvi Support
    url: https://ruuvi.com/support
    email: support@ruuvi.com

servers:
  - url: https://network.ruuvi.com

tags:
  - name: Register-User
  - name: Sensor-Settings


paths:
  /register: 
    $ref: 'register.yaml'
  /sensor-settings:
    $ref: './sensor-settings.yaml'
  /verify: 
    $ref: 'verify.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
