openapi: 3.1.0
info:
  title: Ruuvi Cloud - User API
  description: Ruuvi Cloud user facing API. Everything you need to build your own front-end to Ruuvi Cloud.
  version: 1.0.0
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  contact:
    name: Ruuvi Support
    url: https://ruuvi.com/support
    email: support@ruuvi.com

servers:
  - url: https://network.ruuvi.com
  - url: https://testnet.ruuvi.com

tags:
  - name: Air-Firmware
    description: Ruuvi Air firmware update information
  - name: Alerts
    description: Alert management for sensors
  - name: Register-User
    description: User registration and verification
  - name: Sensor-Settings
    description: Sensor settings management
  - name: Push-Notifications
    description: Push notification token management
  - name: Share
    description: Sensor sharing and unsharing
  - name: Subscription
    description: User subscription management


paths:
  /air_firmwareupdate:
    $ref: './air-firmware.yaml'
  /alerts:
    $ref: './alerts.yaml'
  /push-register:
    $ref: './push-register.yaml'
  /register: 
    $ref: './register.yaml'
  /sensor-settings:
    $ref: './sensor-settings.yaml'
  /share:
    $ref: './share.yaml'
  /subscription:
    $ref: './subscription.yaml'
  /unshare:
    $ref: './unshare.yaml'
  /verify: 
    $ref: './verify.yaml'
  

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
