openapi: 3.0.3
info:
  title: Ruuvi Cloud - User API
  description: Ruuvi Cloud user facing API. Everything you need to build your own front-end to Ruuvi Cloud.
  version: 1.0.0
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  contact:
    name: Ruuvi Support
    url: https://ruuvi.com/support
    email: support@ruuvi.com

servers:
  - url: https://network.ruuvi.com
  - url: https://testnet.ruuvi.com


tags:
  - name: Register-User
    description: User registration and verification
  - name: Sensor-Settings
    description: Sensor settings management
  - name: Air-Firmware
    description: Ruuvi Air firmware update information


paths:
  /register: 
    $ref: 'register.yaml'
  /sensor-settings:
    $ref: './sensor-settings.yaml'
  /verify: 
    $ref: 'verify.yaml'
  /air_firmwareupdate:
    $ref: 'air-firmware.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
