type: object
allOf:
  - $ref: './SensorBase.yaml'
  - type: object
    required:
      - subscription
      - settings
    properties:
      subscription:
        $ref: './SubscriptionResult.yaml'
      settings:
        $ref: './SettingObject.yaml'